name: BUG报告
description: 报告系统功能异常或错误
title: "[BUG] "
labels: ["bug", "待处理"]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请详细描述遇到的问题
      placeholder: "详细说明出现的异常现象和具体表现"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 请提供详细的操作步骤
      placeholder: |
        1. 执行操作A
        2. 执行操作B  
        3. 观察到异常现象
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期结果
      description: 描述期望的正确行为
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: 实际结果
      description: 描述实际发生的异常情况
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 操作系统、软件版本等相关环境
      placeholder: "操作系统：Windows 11\n软件版本：v1.2.0"
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: 附件信息
      description: 相关截图、日志文件或错误信息
    validations:
      required: false
