name: 技术咨询
description: 技术问题咨询和使用指导
title: "[咨询] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: 问题详情
      description: 详细描述需要解决的问题
      placeholder: "请具体说明遇到的技术问题或需要咨询的内容"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 问题上下文
      description: 提供相关的背景信息和使用场景
      placeholder: "正在做什么操作，在什么环境下出现的问题"
    validations:
      required: true
  - type: textarea
    id: attempts
    attributes:
      label: 已尝试方案
      description: 说明已经尝试过的解决方法
      placeholder: "已经查阅的文档，已经尝试的操作步骤"
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 相关的技术环境和版本信息
    validations:
      required: true
